### ISSUE TITLE
Allow duplicate releases

### ISSUE THREAD

**Issue by asbjornu** [marvinpinto/actions#22]
In some projects I manage, releases and tags are created on GitHub.com, but I would still want to upload release assets automatically when `on: tags` is triggered.

It would, therefore, be great if `action-automatic-releases` had an `allow_duplicates` (or similar) field that could be set to `true` to allow a release to already exist, while still performing all the other tasks it currently does, such as uploading assets to the release.

**Comment by asbjornu** [comment]
I would love to help implement this if I knew what to do in order to produce the expected `dist/index.js` file and then use my forked action in a workflow.

**Comment by marvinpinto** [comment]
Hey @asbjornu!

Thanks for sending a PR and apologies for not getting back to you sooner. I think what you are asking for will probably be out of scope for this project. For example: I'm not sure what it would look like for a release already generated on Github - should the changelog be added? Replace what's currently there? How about assets, should they replace the current assets? Or add to them?

I feel like this might get hairy.

You're welcome to use whatever bits necessary to create an action that does what you need. Testing might be tricky with the monorepo structure but should adapt it to a single-repo structure (like other GitHub Actions). I myself use a separate private repo for runs & testing - I didn't bother documenting that here because it's not trivial to replicate.

I'll do my best to help if you need pointers!

**Comment by asbjornu** [comment]
> should the changelog be added?

If there is no changelog, or the one that exists was added by `action-automatic-releases` (could be "signed" by a simple comment in the description), it should be overwritten. If one exists that wasn't added by `action-automatic-releases`, leave it.

> How about assets, should they replace the current assets?

Since assets are rarely uploaded manually, I'd say replace, yes.

> I feel like this might get hairy.

I don't think this is hairy as long as the behaviour is documented and configurable. The `allow_duplicates` flag would be `false` by default and by turning it to `true`, people should know the effects by reading the documentation.

**Comment by marvinpinto** [comment]
Thanks for your input @asbjornu :+1:

I think the feature you propose would be best implemented in another action. I'd like to keep the scope of this one down as much as possible, to make it easier for me to maintain.
