### ISSUE TITLE
avoid security issue

### ISSUE THREAD

**Issue by davidkarlsen** [marvinpinto/actions#55]
The https://github.com/marvinpinto/action-automatic-releases action fails with:
```
Unable to process command '::set-env name=AUTOMATIC_RELEASES_TAG,::v2.2.5-1' successfully.
```
due to the enforcement of the security mech due to https://github.com/advisories/GHSA-mfwh-5m23-j46w
can you update the actions/code lib?

TIA

**Comment by marvinpinto** [comment]
Hey there, I believe this is already done in https://github.com/marvinpinto/actions/issues/48.

**Comment by davidkarlsen** [comment]
great - could you push out a release? we favour using tag's and rather have dependabot come with PRs for upgrading actions to have a bit of control.

**Comment by Vadorequest** [comment]
I'm still getting errors about this, even though it seems to work.

![image](https://user-images.githubusercontent.com/3807458/102676307-37fe0f80-419d-11eb-968b-e98592038d5d.png)

What's even weirder is that I use the same package in another repo and didn't encounter this issue. 🤔 

See https://github.com/UnlyEd/next-right-now/runs/1579933081?check_suite_focus=true where it fails

By using `latest` instead of `1.1.0`, it got fixed.
https://github.com/UnlyEd/next-right-now/runs/1579948255?check_suite_focus=true

**Comment by gboeing** [comment]
Hi @marvinpinto thanks for the great action. Similar to other folks here, I prefer using tags rather than latest to maintain a stable set of actions in my workflow. Would you mind formally releasing this fix? It's still broken using the most recent `1.1.0` release, but appears fixed in the `latest` release.
