### ISSUE TITLE
Automatic releases: Allow custom commit sha

### ISSUE THREAD

**Issue by jhass** [marvinpinto/actions#56]
I have a workflow that has to commit some changes, as such the commit it builds changes compared to the one it was triggered on. It would be awesome to be able to set the tag on this commit instead of `GITHUB_SHA`.

**Comment by marvinpinto** [comment]
Hey @jhass, I am not sure how I would work that into the automatic releases action. The only thing can think of is: in the build workflow where you commit new changes, you "push" those commits back to github, and then let this action take care of it.

Caveats here is you will probably need to use a Personal Access Token (when pushing from within your build) as otherwise these workflows do not get triggered.

Anyway I suspect there is no easy answer here and this is probably out of scope for this project.

**Comment by jhass** [comment]
It's been ages since I looked at this and my use case just went away with Flutter 2 changing how it deals with translations. But if I remember correctly you're just creating the tag for the workflow run's `$GITHUB_SHA`, right? If so it seems like it shouldn't be too hard to make that an optional parameter to the action instead with `$GITHUB_SHA` as the default value.
